// Copyright 2025 protogo-slice-values contributors
//
// Licensed under the MIT License. See LICENSE file in the project root
// for full license information.

// protogo_values/options.proto defines custom field options for controlling
// value type generation in the protogo-slice-values plugin.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.32.0
// source: proto/protogo_values/options.proto

package protogo_values

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// FieldOptions provides structured options for future extensibility.
// This allows adding new field-level options without defining new extensions.
//
// Example usage:
//
//	repeated Item items = 2 [(protogo_values.field_opts).value_slice = true];
type FieldOptions struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// value_slice controls value vs pointer slice generation
	ValueSlice    *bool `protobuf:"varint,1,opt,name=value_slice,json=valueSlice,proto3,oneof" json:"value_slice,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FieldOptions) Reset() {
	*x = FieldOptions{}
	mi := &file_proto_protogo_values_options_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FieldOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FieldOptions) ProtoMessage() {}

func (x *FieldOptions) ProtoReflect() protoreflect.Message {
	mi := &file_proto_protogo_values_options_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FieldOptions.ProtoReflect.Descriptor instead.
func (*FieldOptions) Descriptor() ([]byte, []int) {
	return file_proto_protogo_values_options_proto_rawDescGZIP(), []int{0}
}

func (x *FieldOptions) GetValueSlice() bool {
	if x != nil && x.ValueSlice != nil {
		return *x.ValueSlice
	}
	return false
}

var file_proto_protogo_values_options_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         50001,
		Name:          "protogo_values.value_slice",
		Tag:           "varint,50001,opt,name=value_slice",
		Filename:      "proto/protogo_values/options.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*FieldOptions)(nil),
		Field:         50002,
		Name:          "protogo_values.field_opts",
		Tag:           "bytes,50002,opt,name=field_opts",
		Filename:      "proto/protogo_values/options.proto",
	},
}

// Extension fields to descriptorpb.FieldOptions.
var (
	// optional bool value_slice = 50001;
	E_ValueSlice = &file_proto_protogo_values_options_proto_extTypes[0]
	// optional protogo_values.FieldOptions field_opts = 50002;
	E_FieldOpts = &file_proto_protogo_values_options_proto_extTypes[1]
)

var File_proto_protogo_values_options_proto protoreflect.FileDescriptor

const file_proto_protogo_values_options_proto_rawDesc = "" +
	"\n" +
	"\"proto/protogo_values/options.proto\x12\x0eprotogo_values\x1a google/protobuf/descriptor.proto\"D\n" +
	"\fFieldOptions\x12$\n" +
	"\vvalue_slice\x18\x01 \x01(\bH\x00R\n" +
	"valueSlice\x88\x01\x01B\x0e\n" +
	"\f_value_slice:@\n" +
	"\vvalue_slice\x12\x1d.google.protobuf.FieldOptions\x18ц\x03 \x01(\bR\n" +
	"valueSlice:_\n" +
	"\n" +
	"field_opts\x12\x1d.google.protobuf.FieldOptions\x18҆\x03 \x01(\v2\x1c.protogo_values.FieldOptionsR\tfieldOpts\x88\x01\x01B>Z<github.com/benjamin-rood/protogo-values/proto/protogo_valuesb\x06proto3"

var (
	file_proto_protogo_values_options_proto_rawDescOnce sync.Once
	file_proto_protogo_values_options_proto_rawDescData []byte
)

func file_proto_protogo_values_options_proto_rawDescGZIP() []byte {
	file_proto_protogo_values_options_proto_rawDescOnce.Do(func() {
		file_proto_protogo_values_options_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_protogo_values_options_proto_rawDesc), len(file_proto_protogo_values_options_proto_rawDesc)))
	})
	return file_proto_protogo_values_options_proto_rawDescData
}

var file_proto_protogo_values_options_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proto_protogo_values_options_proto_goTypes = []any{
	(*FieldOptions)(nil),              // 0: protogo_values.FieldOptions
	(*descriptorpb.FieldOptions)(nil), // 1: google.protobuf.FieldOptions
}
var file_proto_protogo_values_options_proto_depIdxs = []int32{
	1, // 0: protogo_values.value_slice:extendee -> google.protobuf.FieldOptions
	1, // 1: protogo_values.field_opts:extendee -> google.protobuf.FieldOptions
	0, // 2: protogo_values.field_opts:type_name -> protogo_values.FieldOptions
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	2, // [2:3] is the sub-list for extension type_name
	0, // [0:2] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_protogo_values_options_proto_init() }
func file_proto_protogo_values_options_proto_init() {
	if File_proto_protogo_values_options_proto != nil {
		return
	}
	file_proto_protogo_values_options_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_protogo_values_options_proto_rawDesc), len(file_proto_protogo_values_options_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 2,
			NumServices:   0,
		},
		GoTypes:           file_proto_protogo_values_options_proto_goTypes,
		DependencyIndexes: file_proto_protogo_values_options_proto_depIdxs,
		MessageInfos:      file_proto_protogo_values_options_proto_msgTypes,
		ExtensionInfos:    file_proto_protogo_values_options_proto_extTypes,
	}.Build()
	File_proto_protogo_values_options_proto = out.File
	file_proto_protogo_values_options_proto_goTypes = nil
	file_proto_protogo_values_options_proto_depIdxs = nil
}
